#!/bin/bash

docker build \
  -f Dockerfile.build \
  --build-arg CLOUDFLARE_VERSION="$(cat VERSION)" \
  -t solidnerd/cloudflare:build .

docker create --name="cloudflare-build" solidnerd/cloudflare:build
docker cp $(docker ps -ql):/flarectl .

docker build \
  -f Dockerfile \
  --build-arg BUILD_DATE="$(date --rfc-3339=s)" \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  -t $IMAGE_NAME .

docker rm -f cloudflare-build
docker rmi solidnerd/cloudflare:build
rm flarectl